swagger: '2.0'
info:
  title: APICTest_API
  x-ibm-name: apictest-api
  version: 2.0.0
host: $(catalog.host)
schemes:
  - https
basePath: /myapi
produces:
  - application/json
consumes:
  - application/json
security: []
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          version: 2.0.0
          title: invoke
          header-control:
            type: blacklist
            values: []
          parameter-control:
            type: whitelist
            values: []
          timeout: 60
          verb: keep
          cache-response: protocol
          cache-ttl: 900
          stop-on-error: []
          target-url: 'http://dummy.restapiexample.com/api/v1/employees'
  phase: realized
  gateway: datapower-api-gateway
  type: rest
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  properties:
    target-url:
      value: 'https://$(catalog.host)'
      description: The URL of the target service
      encoded: false
tags: []
definitions: {}
paths:
  /getStatus:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
      consumes:
        - application/json
      produces:
        - application/json
